spring.config.import=optional:classpath:application-secret.properties

#server
server.port=${app.port}

#data source
spring.datasource.url=${db.url}
spring.datasource.username=${db.username}
spring.datasource.password=${db.password}
spring.datasource.driver-class-name=${db.driver}