app.port=8080
app.env=dev

db.url=jdbc:mysql://localhost:3306/db_hometrest
db.username=fred
db.password=Sf064822@
db.driver=com.mysql.cj.jdbc.Driver

db.test.url=jdbc:mysql://localhost:3306/db_hometrest_test