CREATE TABLES IF NOT EXISTS accounts(
    account_id CHAR(36) NOT NULL PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE,
    account_typ VARCHAR(20) NOT NULL,
    date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_accounts_users FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);